config/routes.rb
Rails.application.routes.draw do
  resources :albums
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users

 root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    elsif user.role == 'user'
      can :create, [Album, Photo]
      can [:update, :destroy], Album, user_id: user.id
      can :read, :all
    else
      can :read, Album, public: true
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :public, type: Boolean, default: false
  has_many :photos

  validates_presence_of :name
  belongs_to :user
  index({ name: 1, user_id: 1 }, { unique: true })
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  belongs_to :album

  mount_uploader :image, PhotoUploader 
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  # == Devise end ==

  field :name, type: String
  
  ROLES = %w(admin user)
  field :role, type: String

  validates_presence_of :email
  has_many :albums
  index({ email: 1 }, { unique: true })
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  before_action :load_album, only: :create
  load_and_authorize_resource 

  def index
    @albums = @albums.where(user_id: current_user.id)
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @album.save
      redirect_to @album, notice: 'Album was successfully created.'
    else
      render :new
    end
  end

  def update
    if @album.update(album_params)
      redirect_to @album, notice: 'Album was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to albums_url, notice: 'Album was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  end

  def load_album
    # CanCan fix for extra params
    @album = Album.new(album_params)
  end

  # Only allow a trusted parameter "white list" through.
  def album_params
    params.require(:album).permit(:name, :public).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def image
    content = @photo.image.read
    if stale?(etag: content, last_modified: @user.updated_at.utc, public: true)
      send_data content, type: @photo.image.file.content_type, disposition: "inline"
      expires_in 0, public: true
    end
  end

  # TODO rest of controller and form for image uploading

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Allowing logged in users to create new users without devise complaining:
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

  def check_permissions
    authorize! :create, resource
  end

  def sign_up(resource_name, resource)
    # No sing_in (user are created by admin, which should stay logged in after)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user! 
  before_action :load_user, only: :create
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if params[:user][:password].blank?
      [:password, :password_confirmation].collect{ |p| params[:user].delete(p) }
    end
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def load_user
    # CanCan fix for extra params
    @user = User.new(user_params)
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @albums = Album.where(public: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.haml
= form_for @album, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :public, :class => 'control-label'
    .controls
      = f.check_box :public, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), albums_path, :class => 'btn'

app/views/albums/_list.html.haml
- model_class = Album

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:public)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @albums.each do |album|
      %tr
        %td= link_to album.name, album_path(album)
        %td= album.public ? "Yes" : "No"
        %td=l album.created_at
        %td
          = link_to("Edit", edit_album_path(album), class: 'btn btn-mini') if can?(:edit, album)
          = link_to("Delete", album_path(album), method: :delete,
            data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger') if can?(:delete, album)

= link_to("New", new_album_path, class: 'btn btn-primary') if can?(:create, Album)

app/views/albums/edit.html.haml
- model_class = Album
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/albums/index.html.haml
.page-header
  %h1 My Albums

= render "list"

app/views/albums/new.html.haml
- model_class = Album
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/albums/show.html.haml
- model_class = Album
.page-header
  %h1= "Album: #{@album.name}"

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @album.name
%p
  %strong= model_class.human_attribute_name(:user) + ':'
  %br
  = @album.user.email
%p
  %strong= model_class.human_attribute_name(:public) + ':'
  %br
  = @album.public ? "Yes" : "No" 

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), albums_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_album_path(@album), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), album_path(@album), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Monuments"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Monuments
          .container.nav-collapse
            %ul.nav
              %li= link_to "Public Stream", "/"
              %li= link_to "Albums", albums_path
              %li= link_to "Users", users_path
            .nav.navbar-form.pull-right
              %small
                - if user_signed_in?
                  Signed in as #{current_user.email} |
                  \#{link_to "Sign out", destroy_user_session_path, method: :delete}

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "#"
              %li= link_to "Link 2", "#"
              %li= link_to "Link 3", "#"
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Stefan Horning 2015

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :role, :class => 'control-label'
    .controls
      = f.collection_select(:role, User::ROLES, :to_s, :humanize)
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'text_field'
  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:role)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.email, user_path(user)
        %td= user.role
        %td= user.name
        %td= user.last_sign_in_at
        %td
          = link_to("Edit", edit_user_path(user), class: 'btn btn-mini') if can?(:edit, user)
          = link_to("Delete", user_path(user), method: :delete,
            data: { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger') if can?(:delete, user)

= link_to("New", new_user_path, class: 'btn btn-primary') if can?(:create, User)

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @user.role

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/welcome/index.html.haml
%h1 Public Photo Albums

= render 'albums/list'